---
name: "data entry"
description: >-
  Used for non-plant commands for data entry. Plant commands are now in data-entry-plants.yaml.
initiallyActive: false
exclusive: false
commands:
# quicker navigation
  - name: "tick"
    description: >-
      Alternate word for "number". 100 utterance arguments. <p>Other alternates include "take", "pick", "ticket"</p>
    alternates:
      - "take"
      - "pick"
      - "ticket"
    functions:
      - name: "number"
        utteranceArguments: 100
  - name: "down"
    description: >-
      Alternate word for "go down"
    functions:
      - name: "keyPress"
        fixedArguments:
          - "down"
  - name: "up"
    description: >-
      Alternate word for "go up"
    functions:
      - name: "keyPress"
        fixedArguments:
          - "up"
  - name: "left"
    description: >-
      Alternate word for "go left". Can also use "leg", "like"
    alternates:
      - "leg"
      - "like"
    functions:
      - name: "keyPress"
        fixedArguments:
          - "left"
  - name: "right" # The weird html creates a header in the table for the next section
    description: >-
      Alternate word for "go right". Can also use "rye", "ri", "ride"
            <thead>
        <tr>
          <th>Excel Commands</th>
          <th></th>
        </tr>
      </thead>
    alternates:
      - "rye"
      - "ri"
      - "ride"
    functions:
      - name: "keyPress"
        fixedArguments:
          - "right"          
# excel commands
  - name: "sum" # The weird html creates a header in the table for the next section
    alternates:
     - "some"
    description: >-
      Correctly types =SUM()  
            <thead>
        <tr>
          <th>Entering Titles and Numbers</th>
          <th></th>
        </tr>
      </thead>
    functions:
      - name: "type"
        fixedArguments:
         - "=SUM()"
# formatting
  - name: "setup transect titles"
    alternates:
      - "set up transect titles"
    description: >-
      Sets up titles for transects: <br />Common name (tab) Scientific name (tab) Start (tab) End (tab)
    functions:
      - name: "type"
        fixedArguments:
          - "Common name\tScientific name\tStart\tEnd"
  - name: "no border"
    description: >-
      Clears the border around the selected cells. Equivalent to alt, h, b, n
    # alternates: 
    functions:
      - name: "keyPress"
        fixedArguments:
          - "alt"
      - name: "keyPress"
        fixedArguments:
          - "h"
      - name: "keyPress"
        fixedArguments:
          - "b"
      - name: "keyPress"
        fixedArguments:
          - "n"
  - name: "outside border"
    description: >-
      Adds outside border around the selected cells. Equivalent to alt, h, b, s
    # alternates: 
    functions:
      - name: "keyPress"
        fixedArguments:
          - "alt"
      - name: "keyPress"
        fixedArguments:
          - "h"
      - name: "keyPress"
        fixedArguments:
          - "b"
      - name: "keyPress"
        fixedArguments:
          - "s"
  - name: "highlighter"
    description: >-
      Opens highlight options. Equivalent to alt, h, h
    # alternates: 
    functions:
      - name: "keyPress"
        fixedArguments:
          - "alt"
      - name: "keyPress"
        fixedArguments:
          - "h"
      - name: "keyPress"
        fixedArguments:
          - "h"
  - name: "no fill"
    alternates:
      - "no phil"
      - "no fail"
    description: >-
      Highlights without fill. Equivalent to alt, h, h, n
    functions:
      - name: "keyPress"
        fixedArguments:
          - "alt"
      - name: "keyPress"
        fixedArguments:
          - "h"
      - name: "keyPress"
        fixedArguments:
          - "h"
      - name: "keyPress"
        fixedArguments:
          - "n"         
  - name: "highlight grey"
    alternates:
      - "highlight gray"
    description: >-
      Highlights the third grey option down. Equivalent to alt, h, h, down three, enter
    functions:
      - name: "keyPress"
        fixedArguments:
          - "alt"
      - name: "keyPress"
        fixedArguments:
          - "h"
      - name: "keyPress"
        fixedArguments:
          - "h"
      - name: "keyRepeat"
        fixedArguments:
          - "down"
          - "3"
      - name: "keyPress"
        fixedArguments:
          - "enter"
# numbers
  - name: "line" #for transacts
    description: >-
      Use this command to type a line for transect data.
      <p>Saying "line 1.1 stop 2.2" gives you:</p>
      1.1 (tab) 2.2 (enter)
      <p>You can try using it multiple times in a row, but it might not work correctly.
      <br />Saying "line 1.1 stop 2.2 stop line 3.3 stop 4.4 stop" should give you:</p>
      <p>1.1 (tab) 2.2 (enter)
      <br />3.3 (tab) 4.4 (enter)</p>
    alternates: 
      - "mine" #frequently mis-recognized
    functions:
      - name: "number"
        utteranceArguments: 1
      - name: "type"
        fixedArguments:
          - "\t" # goes to next cell in Excel
      - name: "number"
        utteranceArguments: 1
      - name: "type"
        fixedArguments:
          - "\n" # equivalent to 'Enter' in Excel


#  - name: "telephone number"
#    description: >-
#      Use this command to type a telephone number in the N-N-N format.
#      The first utterance argument is the first number.
#      The second utterance argument is "stop".
#      The third utterance argument is the second number.
#      The fourth utterance argument is "stop".
#      The fifth utterance argument is the third number.
#    functions:
#      - name: "number"
#        utteranceArguments: 1
#      - name: "type"
#        fixedArguments:
#          - "-"
#      - name: "number"
#        utteranceArguments: 1
#      - name: "type"
#        fixedArguments:
#          - "-"
#      - name: "number"
#        utteranceArguments: 1
#    spaceLeft: true
#    spaceRight: true
